### ISSUE TITLE
Should default IdentityStoreHandler return all (or most) fields of CredentialValidationResult?

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-spec#44]
The spec currently says that the default `IdentityStoreHandler` returns only caller principal and groups, explicitly states `callerUniqueId` and `storeId` are not returned.

At minimum, needs update for completeness if we only return caller principal and groups.

Should it also specify that other fields -- all of them, or perhaps just `callerUniqueId` and `callerDn` -- are returned as well? These fields could potentially be very useful to authentication mechanisms; WebLogic, for example, includes GUID and DN fields in it's platform principals, so if these values are present it seems wasteful not to make them available to the authentication mechanism, which might otherwise need to make another call to the user store without an obvious way to identify which store to query.

**Comment by arjantijms** [comment]
Could it perhaps be an option to add a `Principal getWrapped()` to CallerPrincipal?

**Comment by wmhopkins** [comment]
Certainly that's possible, but it would seem to complicate the interface -- why not just return the values directly, since they're there in the CVR, and let the authentication mechanism choose which fields were of interest, without having to wrap/unwrap principals and potentially instantiate a new principal just to get rid of fields may not be wanted?

**Comment by ggam** [comment]
Would this include an arbitrary set of fixed fields? Or would this be e.g. a HashMap of values?

**Comment by wmhopkins** [comment]
It would be the existing fields in the `CredentialValidationResult`. At the moment, these are not returned to the caller of `IdentityStoreHandler.validate()` even if they are returned by the `IdentityStore`.

**Comment by arjantijms** [comment]
I don't have the source for me here at the moment, but from the top of my head I think this should be possible.

At the very least, there's always the escape hatch of people who really need this to write their own `IdentityStoreHandler`, although that should be a solution of last resort for this particular problem.

**Comment by wmhopkins** [comment]
It's easily possible -- just copy the values returned by the validating `IdentityStore` when creating the CVR to return from `IdentityStoreHandler`. There is the obvious workaround you mention, but this is such a simple thing it seems silly to make people write a whole new `IdentityStoreHandler` just to get the data that's already returned by the `IdentityStore`. (Of course, not all `IdentityStore`s will return those values, but if they do, it's a simple matter to pass them on, along with the `CallerPrincipal` and groups.)

**Comment by arjantijms** [comment]
I agree, this would not hurt or complicate things as far as I can see. Just make sure the spec says that it are the values from the store that successfully validated the credentials to avoid confusion.

**Comment by wmhopkins** [comment]
OK, sounds good.

**Comment by wmhopkins** [comment]
Fixed by #58 .
