### ISSUE TITLE
Make sure SecurityContext.getCallerPrincipal() is correctly described for anonymous

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-spec#53]
In EJB container, returns null, not anonymous principal, but make sure we don't describe anonymous principal as "null or empty", since EJB spec allows any value there.

**Comment by arjantijms** [comment]
Indeed, the SecurityContext#getCallerPrincipal MUST return null if the caller is not authenticated, no matter the container.

Servlet simply says:

"null if the user has not been authenticated"

http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal--

The EJB native call is very problematic, as it says:

"This method never returns null."

http://docs.oracle.com/javaee/7/api/javax/ejb/EJBContext.html#getCallerPrincipal--

I'm sure EJB intended this well at the time, but the pain, bugs and hours of wasted time this has caused is probably hard to describe.

JSR 196 uses the term "unauthenticated caller principal".

Also note that our requirement EXCLUSIVELY entails for what `SecurityContext#getCallerPrincipal` returns. The container is still allowed to have its own representation of the unauthenticated caller principal within the `Subject`. Like Servlet, the spec text for `SecurityContext#getCallerPrincipal` should simply be silent on that aspect.

**Comment by wmhopkins** [comment]
Right, we will always return null, and I think the spec says that, I just want to make sure we don't mischaracterize the EBJ behavior; I had thought it would return a Principal with a null or empty name, but it turns out it can be whatever value the vendor chooses.

As an aside, I tried to figure out what GF was  doing today; I didn't fully figure it out, but I think it's possible that it's configurable, or that it depends on the implementation of the authentication realm. That will be very hard to deal with in the RI.

**Comment by arjantijms** [comment]
>That will be very hard to deal with in the RI.

I think it will not be terribly hard. Basically all one has to do is look at the implementation of the existing `EJBContext#getCallerPrincipal`, at that point the code in that implementation knows what the anonymous principal is. The code here in the JSR 375 _SecurityContext_ can do the same (obtain the current representation of the anonymous principal) and then compare its outcome to what EJBContext#getCallerPrincipal` returns.

But, don't forget that getting the caller principal via `EJBContext#getCallerPrincipal` is basically just a, more or less, portable fallback. A true implementation of an SPI for Soteria (or code used when a vendor implements JSR 375 or parts of it independently) could use the direct proprietary methods that every container has.

As an aside from my side, I have to do the same work when I further integrate Soteria into the Payara server ;)

**Comment by wmhopkins** [comment]
Fixed by #58 .
