### ISSUE TITLE
Permission based authorization

### ISSUE THREAD

**Issue by mmotwakel** [javaee/security-spec#67]
Will permission based autherization be supported by next versions?

**Comment by arjantijms** [comment]
There are already Permissions being used, see e.g. `javax.security.jacc.WebRoleRefPermission`, but in the next version the entire topic of authorization will indeed be expanded upon. 

For a glimpse, see this prototype that didn't make it into 1.0: http://arjan-tijms.omnifaces.org/2016/07/simplified-custom-authorization-rules.html

**Comment by githubabcde** [comment]
Thank You Arjan,

I read your example that really helps.

**Comment by mmotwakel** [comment]
thank you Arjan

your example is helpful
